name: Feather-Utilities
version: 1.0-SNAPSHOT
main: org.yuemi.feather.Main
api-version: 1.21.4
authors: 
- YueMi
- NekoMonci12
description: An Minecraft Plugin For Managing Feather Client API Features
